name: tilt
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sensors_plus: ^1.3.0
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.recki.tilt
        pluginClass: TiltPlugin
      ios:
        pluginClass: TiltPlugin
      web:
        pluginClass: TiltWeb
        fileName: tilt_web.dart
